version: '3.7'

services:
    thermal_ai:
        build: thermal_ai/.
        command: gunicorn --bind 0.0.0.0:5000 manage:app
        volumes:
            - ./static:/home/app/web/static
            - ./templates:/home/app/web/templates
        expose:
            - "5000"
        depends_on:
            - postgres
        env_file: .env.prod
    postgres:
        image: postgres:12-alpine
        volumes:
            - /home/gmnx/thermal-ai/portal/postgres_data:/var/lib/postgresql/data
        restart: always
        env_file: .env.prod.postgres
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
    nginx:
        build: ./nginx
        volumes:
            - ./static:/home/app/web/static
            - ./templates:/home/app/web/templates
        ports:
            - 3000:3000
        depends_on:
            - thermal_ai
volumes:
    postgres_data:
